appProyectos/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import ProyectoCreate,ProyectoDetailView,ProyectoUpdate, ProyectoDeleteView

urlpatterns = [
    path('register/',ProyectoCreate.as_view() , name='proyecto-register'),
    path("ver/<int:pk>/", login_required(ProyectoDetailView.as_view(template_name="proyecto/ver-proyecto.html")), name="proyecto-ver"),
    path("<int:pk>/update/", ProyectoUpdate.as_view(), name="proyecto-update"),
    path("eliminar/<int:pk>/", ProyectoDeleteView.as_view(), name="proyecto-delete"),
    path("detail/<int:pk>/", ProyectoDetailView.as_view(template_name="proyecto/portafolio-detail.html"), name="proyecto-detail")
]

appUser/urls.py
from django.urls import path
from . import views 
urlpatterns = [
    path('profile/',views.profile,name="user-profile" ),
]

djangoPorfolio/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import include, path
from appProyectos.views import index

from appUser import views as user_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("proyecto/", include("appProyectos.urls")),
    path("user/", include("appUser.urls")),
    path("register/", user_views.registerPage, name="user-register"),
    path("login/",auth_views.LoginView.as_view(template_name="user/login.html"),name="login-page",),
    path("logout/",auth_views.LogoutView.as_view(template_name="user/logout.html"),name="logout",),
    path("", index, name="home-page"),
    path("portafolio/<int:pk>/",user_views.UserDetailsTemplate.as_view(),name="portafolio",),
]
handler404 = "djangoPorfolio.views.page_not_found_view"
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appProyectos/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.urls  import reverse
from io import BytesIO
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage as storage   
# Create your models here.


class Proyecto(models.Model):
    """Model definition for Proyecto."""

    # TODO: Define fields here
    title = models.CharField(max_length=100)
    descripcion = models.TextField()
    foto_img = models.ImageField(upload_to="proyect_file",blank=True,null=True)
    foto_url = models.CharField(max_length=500,blank=True)
    git = models.CharField(max_length=500)
    tags = models.CharField(max_length=500)
    autor = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        """Meta definition for Proyecto."""

        # db_table = "proyectos"
        verbose_name = "Proyecto"
        verbose_name_plural = "Proyectos"

    def __str__(self):
        """Unicode representation of Proyecto."""
        return self.title

    def get_absolute_url(self):
        return reverse("proyecto-ver", kwargs={"pk": self.pk})

    def save(self,*args, **kwargs):
        super(Proyecto,self).save(*args, **kwargs)
        if self.foto_img:
            # After save, read the file
            image_read = storage.open(self.foto_img.name, "r")
            image = Image.open(image_read)
            if image.height > 300 or image.width > 300:
                size = 300, 300
                # Create a buffer to hold the bytes
                imageBuffer = BytesIO()
                # Resize  
                image.thumbnail(size, Image.ANTIALIAS)
                # Save the image as jpeg to the buffer
                image.save(imageBuffer, image.format)
                # Save the modified image
                proyecto = Proyecto.objects.get(pk=self.pk)
                proyecto.foto_img.save(self.foto_img.name, ContentFile(imageBuffer.getvalue()))

                image_read = storage.open(proyecto.foto_img.name, "r")
                image = Image.open(image_read)
            image_read.close()

appProyectos/forms.py
from django import forms

from appProyectos.models import Proyecto

class ProyectoForm(forms.ModelForm):
    """ProyectoForm definition."""

    # TODO: Define form fields here
    # Título del proyecto
    title = forms.CharField(label="Titulo", max_length=200, widget=forms.TextInput(attrs={'class': 'form-control'}))
    #Descripción del proyecto
    descripcion=forms.CharField(label="Descripción",widget=forms.Textarea(attrs={'class': 'form-control',"rows":3}))
    #Tags: HTML, CSS, PYTHON, etc
    tags = forms.CharField(label="Tags",max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    #Foto (que puede ser una URL)
    foto_url = forms.URLField(label="Foto",required=False,widget=forms.URLInput(attrs={'class': 'form-control',"placeholder":"https://..."}))
    foto_img = forms.ImageField(required=False,widget=forms.FileInput(attrs={'class': 'form-control'}))
    #URL de github
    git = forms.URLField(label="Url de Git",widget=forms.URLInput(attrs={'class': 'form-control',"placeholder":"https://..."}))
    #Formulario con validación
    class Meta:
        model=Proyecto #USER DE DJANGO
        fields=['title','descripcion','tags','foto_img','foto_url','git']

    def clean(self):
       cleaned_data = self.cleaned_data
       uploadedfile = cleaned_data.get("foto_img")
       url_address = cleaned_data.get("foto_url")
       
       if not uploadedfile and not url_address :
           raise forms.ValidationError("El campo de foto es obligatorio, ingresa una URL válida o carga una foto")
       return cleaned_data 

appProyectos/views.py
from django.http import HttpRequest
from django.shortcuts import  render
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.views.generic import CreateView,DetailView, UpdateView,DeleteView
from django.contrib.auth.decorators import login_required
from appProyectos.forms import  ProyectoForm

from appProyectos.models import Proyecto
# Create your views here.
@login_required
def index(request):
    current_user=request.user
    context={
        "proyectos": current_user.proyecto_set.all(),
        "cantidad":current_user.proyecto_set.count(),
        "visitantes":current_user.visitanteportafolio_set.count(),
        "dashboard":"dashboard"
    }

    return render(request,"proyecto/index.html",context)


class ProyectoCreate(LoginRequiredMixin,SuccessMessageMixin,CreateView):
    form_class=ProyectoForm
    template_name = 'proyecto/form-proyecto.html'
    success_url = '/'
    success_message = "Se ha registrado tu proyecto correctamente"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['name'] = "Registrar"
        context['registrar']="registrar"
        return context
    
    def form_valid(self,form):
        form.instance.autor=self.request.user
        return super().form_valid(form)

class ProyectoUpdate(LoginRequiredMixin,SuccessMessageMixin,UserPassesTestMixin,UpdateView):
    form_class=ProyectoForm
    model=Proyecto
    template_name = 'proyecto/form-proyecto.html'
    success_message = "Se ha actualizado su proyecto correctamente"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['name'] = "Actualizar"
        if context.get("proyecto").foto_img:
            context["url_img"]=context.get("proyecto").foto_img.url
        return context

    def form_valid(self,form):
        form.instance.autor=self.request.user
        if form.instance.foto_url:
            form.instance.foto_img=None
        return super().form_valid(form)

    def test_func(self):
        proyecto=self.get_object()
        if self.request.user==proyecto.autor:
            return True
        return False

class ProyectoDetailView(DetailView):
    model=Proyecto
    #template_name='proyecto/ver-proyecto.html'
    context_object_name="proyecto"

class ProyectoDeleteView(UserPassesTestMixin,LoginRequiredMixin,DeleteView):
    model=Proyecto
    template_name='proyecto/delete-proyecto.html'
    context_object_name="proyecto"
    success_url="/"
    
    def test_func(self):
        proyecto=self.get_object()
        if self.request.user==proyecto.autor:
            return True
        return False

appProyectos/templates/proyecto/base-login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>{% block title %}{% endblock title %}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %} " rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %} " rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %} " rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %} " rel="stylesheet">
  

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: NiceAdmin - v2.4.1
  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>
  
    {% block container %}
    
    {% endblock container %}
        
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

appProyectos/templates/proyecto/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>{% block title %}{% endblock title %}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %} " rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %} " rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %} " rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %} " rel="stylesheet">
  <link href="{% static 'assets/vendor/simple-datatables/style.css' %} " rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: NiceAdmin - v2.4.1
  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>
    {% include 'proyecto/header.html' %}
    {% block content %}
        
    {% endblock content %}
    {% include 'proyecto/footer.html' %}
    <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>
</body>

</html>

appProyectos/templates/proyecto/delete-proyecto.html
{% extends 'proyecto/base.html' %}
{% block title %}
Delete Project - PortafolioAdmin 
{% endblock title %}
{% block content %}
  {% include 'proyecto/siderbar.html' %}
  <main>
    <div class="container">
      
      <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-lg-6 col-md-6 d-flex flex-column align-items-center justify-content-center">
              
              <div class="card mb-3">

                <div class="card-body">

                  <div class="pt-4 pb-2">
                    <h5 class="card-title text-center pb-0 fs-4">¿Está seguro?</h5>
                    <p class="text-center small">¿Está usted seguro que quiere eliminar su proyecto <strong>"{{ proyecto.title }}"</strong>?</p>
                  </div>
                  <form method="post">
                        {% csrf_token %}
                      <div class="row">
                          <div class="col-6">
                              <button class="btn btn-danger w-100" type="submit">Sí, eliminar</button>
                            </div>
                            <div class="col-6">
                                <a class="btn btn-secondary w-100" href="{% url 'proyecto-ver' proyecto.id %}">No, regresar</a>
                            </div>
                        </div>
                    </div>
                   </form>
              </div>

              <div class="credits">
                <!-- All the links in the footer should remain intact. -->
                <!-- You can delete the links only if you purchased the pro version. -->
                <!-- Licensing information: https://bootstrapmade.com/license/ -->
                <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
                Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
              </div>

            </div>
          </div>
        </div>

      </section>

    </div>
  </main><!-- End #main -->
{% endblock content %}

appProyectos/templates/proyecto/footer.html
<!-- ======= Footer ======= -->
<footer id="footer" class="footer">
    <div class="copyright">
      &copy; Copyright <strong><span>NiceAdmin</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
      <!-- All the links in the footer should remain intact. -->
      <!-- You can delete the links only if you purchased the pro version. -->
      <!-- Licensing information: https://bootstrapmade.com/license/ -->
      <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
      Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

appProyectos/templates/proyecto/form-proyecto.html
{% extends 'proyecto/base.html' %} 
{% block title %}
Project - PortafolioAdmin 
{% endblock title %}
{% block content %} 
    {% include 'proyecto/siderbar.html' %} 
    <main id="main" class="main">

        <div class="pagetitle">
          <h1>Proyecto</h1>
          <nav>
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{% url 'home-page' %}">Home</a></li>
              <li class="breadcrumb-item">Proyectos</li>
              <li class="breadcrumb-item active">{{ name }}</li>
            </ol>
          </nav>
        </div><!-- End Page Title -->
    
        <section class="section">
          <div class="row">
            <div class="col-lg-12">
    
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title">{{ name }} Proyecto</h5>
                  {% if form.errors %}
                  <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <h4 class="alert-heading">Por favor corrige los siguientes errores</h4>
                    <hr>
                    <ul>
                      {% for field in form %}
                        {% if field.errors %}
                            {% for error in field.errors %}
                                <p> <i class="bi bi-x-circle-fill"></i> {{ field.label }}: <a href="#id_{{ field.name }}" class="text-danger">{{ error|escape }}</a> </p>
              
                            {% endfor %}
                        {% endif %}
                      {% endfor %}
                    </ul>
                    {% if form.non_field_errors %}
                    <ul>
                      {% for error in form.non_field_errors %}
                      <p> <i class="bi bi-x-circle-fill"></i> {{ error }} </p>
                      {% endfor %}
                    </ul>
                    {% endif %}
                  </div>
                  {% endif %}
                  
                  <!-- General Form Elements -->
                  <form method="post" enctype="multipart/form-data" novalidate>
                    {% csrf_token %}
                    
                    <div class="row mb-3">
                      <label for="titulo" class="col-sm-2 col-form-label">{{ form.title.label }}</label>
                      <div class="col-sm-10">
                        {{ form.title }}
                      </div>
                    </div>
                    <div class="row mb-3">
                      <label for="tags" class="col-sm-2 col-form-label">{{ form.tags.label }}</label>
                      <div class="col-sm-10">
                        {{ form.tags }}
                      </div>
                    </div>
                    <div class="row mb-3">
                        <label for="descripcion" class="col-sm-2 col-form-label">{{ form.descripcion.label }}</label>
                        <div class="col-sm-10">
                            {{ form.descripcion }}
                        </div>
                    </div>
                    <div class="row mb-3 ">
                      <label for="foto" class="col-sm-2 col-form-label">{{ form.foto_url.label }}</label>
                      <div class="w-50">
                        <div class="form-check form-check-inline  mb-0">
                          <input class="form-check-input" type="radio" name="inlineRadioOptions" id="urlImg" value="option1">
                          <label class="form-check-label" for="inlineRadio1">Subir URL de una imagen</label>
                        </div>
                        <div class="form-check form-check-inline mb-0">
                          <input class="form-check-input" type="radio" name="inlineRadioOptions" id="realImg" value="option2">
                          <label class="form-check-label" for="inlineRadio2">Cargar una imagen</label>
                        </div>
                      </div>
                    </div>
                    <div class="row mb-3" style="display: none;" id="inputUrlImg">
                      <label for="url_img" class="col-sm-2 col-form-label">Url Foto</label>
                      <div class="col-sm-10">
                        {{ form.foto_url }}
                      </div>
                    </div>
                    <div class="row mb-3" style="display: none;" id="inputFileImg">
                      <label for="upload_foto" class="col-sm-2 col-form-label">Upload Foto</label>
                      <div class="col-sm-10">
                        {{ form.foto_img }}
                      </div>
                      <div class="col-sm-10 mt-3 d-flex justify-content-center">
                        {% if url_img %}
                          <span>Foto actual: </span><img src="{{ url_img }}" class="img-thumbnail rounded float-start" style="max-width: 220px;" id="imagenPrevisualizacion">
                        {% else %}
                          <img class="img-thumbnail rounded float-start" style="max-width: 220px;" id="imagenPrevisualizacion">
                        {% endif %}
                      </div>
                    </div>
                    <div class="row mb-3">
                      <label for="git" class="col-sm-2 col-form-label">{{ form.git.label }}</label>
                      <div class="col-sm-10">
                        {{ form.git }}
                      </div>
                    </div>
                    <div class="row mb-3">
                      <div class="col-sm-10 text-center">
                        <button type="submit" class="btn btn-primary">{{ name }}</button>
                      </div>
                    </div>
    
                  </form>
                  <!-- End General Form Elements -->
    
                </div>
              </div>
    
            </div>
          </div>
        </section>
    
      </main><!-- End #main -->
<script>
  document.addEventListener("DOMContentLoaded", function(event) {
    // Your code to run since DOM is loaded and ready
    var $seleccionArchivos = document.querySelector("#id_foto_img");
    var $urlValor=document.getElementById("id_foto_url");
    var $imagenPrevisualizacion = document.querySelector("#imagenPrevisualizacion");
    var url = document.getElementById('inputUrlImg');
    var file = document.getElementById('inputFileImg');
    var archivoF="{{ form.foto_img.value }}"
    console.log(archivoF)
  if ($urlValor.value!=""){
    document.getElementById("urlImg").checked = true;
    clickUrl()
  }else if (archivoF!="None" &&  archivoF!=""  ){
    console.log(archivoF)
    document.getElementById("realImg").checked = true;
    clickImg()
  }
  document.getElementById("urlImg").onclick = function(){//do something
    clickUrl()
  }
  function clickUrl(){
    url.style.removeProperty("display");
    file.style.display="none";
    $seleccionArchivos.value = "";
    $imagenPrevisualizacion.src = "";
  }
  document.getElementById("realImg").onclick = function(){//do something
    clickImg()
  }
  function clickImg(){
    file.style.removeProperty("display");
    url.style.display="none"
    $urlValor.value = "";
  }
// Escuchar cuando cambie
  $seleccionArchivos.addEventListener("change", () => {
    // Los archivos seleccionados, pueden ser muchos o uno
    const archivos = $seleccionArchivos.files;
    // Si no hay archivos salimos de la función y quitamos la imagen
    if (!archivos || !archivos.length) {
      $imagenPrevisualizacion.src = "";
      return;
    }
    // Ahora tomamos el primer archivo, el cual vamos a previsualizar
    const primerArchivo = archivos[0];
    // Lo convertimos a un objeto de tipo objectURL
    const objectURL = URL.createObjectURL(primerArchivo);
    // Y a la fuente de la imagen le ponemos el objectURL
    $imagenPrevisualizacion.src = objectURL;
  });
});
</script>
{% endblock content %}

appProyectos/templates/proyecto/header.html
{% load static %}
<!-- ======= Header ======= -->
<header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="{% url 'home-page' %}" class="logo d-flex align-items-center">
        <img src="{% static 'assets/img/logo.png' %}" alt="">
        <span class="d-none d-lg-block">PorfolioNav</span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">
        <li class="nav-item dropdown pe-3">
          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
            <img src="{{ user.profile.image.url }} " alt="Profile" class="rounded-circle">
            <span class="d-none d-md-block dropdown-toggle ps-2">{{ user.username }}</span>
          </a><!-- End Profile Iamge Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li class="dropdown-header">
              {% if user.last_name %}
                <h6>{{ user.last_name }} </h6>
              {% else %}
                <h6>{{ user.username }} </h6>
              {% endif %}
              <span>Web Designer</span>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="{% url 'user-profile' %}">
                <i class="bi bi-person"></i>
                <span>My Profile</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="{% url 'logout' %}">
                <i class="bi bi-box-arrow-right"></i>
                <span>Cerrar sesión</span>
              </a>
            </li>

          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->

      </ul>
    </nav><!-- End Icons Navigation -->

  </header><!-- End Header -->

appProyectos/templates/proyecto/index.html
  {% extends 'proyecto/base.html' %}
  {% block title %}
  Dashboard - PortafolioAdmin 
  {% endblock title %}
  
  {% block content %}
    {% include 'proyecto/siderbar.html' %}
    <main id="main" class="main">

      <div class="pagetitle">
        <h1>Dashboard</h1>
        <nav>
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'home-page' %}">Home</a></li>
            <li class="breadcrumb-item active">Dashboard</li>
          </ol>
        </nav>
      </div><!-- End Page Title -->
      <!-- FLASH MESSAGES -->
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
  {% endif %}
  <!-- END -->
      <section class="section dashboard">
        <div class="row">
          
          <!-- Left side columns -->
          <div class="col-lg-12">
            <div class="row">
  
              <!-- Sales Card -->
              <div class="col-xxl-6 col-md-6">
                <div class="card info-card sales-card">
                  <div class="card-body">
                    <h5 class="card-title">Proyectos Registrados</h5>
                    <div class="d-flex align-items-center">
                      <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                        <i class="bi bi-save-fill"></i>
                      </div>
                      <div class="ps-3">
                        <h6>{{ cantidad }}</h6>
                        <span class="text-muted small pt-2 ps-1">Proyectos que has registrado</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div><!-- End Sales Card -->
  
              <!-- Revenue Card -->
              <div class="col-xxl-6 col-md-6">
                <div class="card info-card revenue-card">
                  <div class="card-body">
                    <h5 class="card-title">Visitantes en tu portafolio</h5>
  
                    <div class="d-flex align-items-center">
                      <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                        <i class="bi bi-people-fill"></i>
                      </div>
                      <div class="ps-3">
                        <h6>{{ visitantes }}</h6>
                        <span class="text-muted small pt-2 ps-1">Personas que visitaron tu portafolio</span>
  
                      </div>
                    </div>
                  </div>
  
                </div>
              </div><!-- End Revenue Card -->
  
            <!-- Recent Sales -->
              <div class="col-12">
                <div class="card recent-sales overflow-auto">
  
                  <div class="filter">
                    <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                      <li class="dropdown-header text-start">
                        <h6>Filter</h6>
                      </li>
  
                      <li><a class="dropdown-item" href="#">Today</a></li>
                      <li><a class="dropdown-item" href="#">This Month</a></li>
                      <li><a class="dropdown-item" href="#">This Year</a></li>
                    </ul>
                  </div>
  
                  <div class="card-body">
                    <h5 class="card-title">Tus Proyectos </h5>
  
                    <table class="table table-borderless datatable">
                      <thead>
                        <tr>
                          <th scope="col">#</th>
                          <th scope="col">Titulo</th>
                          <th scope="col">Tags</th>
                          <th scope="col">Git</th>
                          <th scope="col">Acciones</th>
                        </tr>
                      </thead>
                      <tbody>
                        
                        {% for proyecto in proyectos %}
                          <tr>
                            <th scope="row"># {{ proyecto.id }}</th>
                            <td>{{ proyecto.title }}</td>
                            <td>{{ proyecto.tags }}</td>
                            <td>
                              <a href="{{ proyecto.git }}" class="twitter" target="_blank"><i class="bi bi-github"></i></a>
                            </td>
                            <td style="width: 17%;">
                              <a href="{% url 'proyecto-ver' proyecto.id %}" class="btn btn-success"><i class="bi bi-eye-fill"></i></a>
                              <a href="{% url 'proyecto-update' proyecto.id %}" class="btn btn-warning"><i class="bi bi-pencil-fill"></i></a>
                              <a href="{% url 'proyecto-delete' proyecto.id %}" class="btn btn-danger"><i class="bi bi-x-circle-fill"></i></a>
                            </td>
                          </tr>
                        {% endfor %}
                          
                      </tbody>
                    </table>
                  </div>
                </div>
              </div><!-- End Recent Sales -->
            </div>
          </div><!-- End Left side columns -->
        </div>
      </section>
  
    </main><!-- End #main -->
  {% endblock content %}